### ISSUE TITLE
Openvpn

### ISSUE THREAD

**Issue by jonkodi-67** [CoreELEC/addons-archive#1]
I run a Kodi X96 max media box.
Distribution: CoreELEC (official)
Version: 20.2 nexus.
Arkitektur: Amlogic-ng.arm

As I understand it, the best way to attach my NordVPN account and run it on my media box, is to set it up with Openvpn, wich I thought was preinstalled in the build. 
I’ve tried to install openvpn but it just don’t work. I installed: https://github.com/repository.zomboided.plugins-1.0.0.zip
But it just wont open. 
Do I need to install an addon.. to be able to install things??
Please advise!
/Jonas

**Comment by vpeter4** [comment]
Use forum for support.
